name: GNU GCC (Ubuntu)

on: [push, pull_request]

jobs:
  debug_x64:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: setup
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10 gcc-10-multilib g++-10-multilib
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

    - name: premake 
      run: |
        curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
        7z x premake.tar.gz
        7z x premake.tar
        chmod 777 premake5
        ./premake5 gmake2 --output_directory=output

    - name: build
      run: make config=debug_x64 -C build
      
    - name: test
      run: ./output/test_exception_manager

  release_x64:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: setup
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10 gcc-10-multilib g++-10-multilib
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

    - name: premake 
      run: |
        curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
        7z x premake.tar.gz
        7z x premake.tar
        chmod 777 premake5
        ./premake5 gmake2 --output_directory=output

    - name: build
      run: make config=release_x64 -C build
      
    - name: test
      run: ./output/test_exception_manager

  debug_x86:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: setup
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10 gcc-10-multilib g++-10-multilib
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

    - name: premake 
      run: |
        curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
        7z x premake.tar.gz
        7z x premake.tar
        chmod 777 premake5
        ./premake5 gmake2 --output_directory=output

    - name: build
      run: make config=debug_x86 -C build
      
    - name: test
      run: ./output/test_exception_manager

  release_x86:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: setup
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-10 g++-10 gcc-10-multilib g++-10-multilib
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

    - name: premake 
      run: |
        curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
        7z x premake.tar.gz
        7z x premake.tar
        chmod 777 premake5
        ./premake5 gmake2 --output_directory=output

    - name: build
      run: make config=release_x86 -C build
      
    - name: test
      run: ./output/test_exception_manager
